Smithy/Smithy/urls.py
from django.contrib import admin
from django.urls import path, include
# hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('seller.urls')),
]

Smithy/seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'

urlpatterns = [

    path('seller/', views.dashboard, name='dashboard'),
    path('products/', views.products, name='products'),
    path('performance/', views.performance, name='performance'),
    path('seller-orders/', views.seller_orders, name='seller-orders'),
    path('seller-profile/', views.seller_profile, name='seller-profile'),
    path('help-center/', views.help_center, name='help-center'),
    path('seller-delete/', views.seller_delete, name='seller-delete'),
    path('add-products/', views.add_products, name='add-products'),
]

Smithy/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('tools/', views.tools, name='tools'),
    path('agriculture/', views.agriculture, name='agriculture'),
    path('weapones/', views.weapones, name='weapones'),
    path('utensils/', views.utensils, name='utensils'),
    path('login/', views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
    path('wishlist/',views.wishlist, name='wishlist'),
    path('logout/', views.logout_page, name="logout"),
    path('payment/', views.pay_now, name="payment"),
    path('profile/', views.profile, name="profile"),
    path('orders/', views.orders, name="orders"),

    
    path('product-details/<product_id>',views.product_details,name='product_details'),
    path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    path('cart/',views.show_cart,name='showcart'),
    path('delete-from-cart/',views.delete_from_cart,name='delete-from-cart'),
    path('increase_quantity/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease_quantity/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    

]

Smithy/seller/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product



class SellerOrder(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('shipped', 'Shipped'),
        ('delivered', 'Delivered'),
        ('cancelled', 'Cancelled'),
    )

    # PAYMENT_CHOICES = (
    #     ('credit_card', 'Credit Card'),
    #     ('paypal', 'PayPal'),
    #     ('cash_on_delivery', 'Cash on Delivery'),
    # )

    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seller_orders')
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='buyer_orders')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    # payment_method = models.CharField(max_length=20, choices=PAYMENT_CHOICES)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_id = models.CharField(max_length=100)
    address_line = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=10)
    mob = models.CharField(max_length=10)

    def __str__(self):
        return f"Order #{self.pk} - Seller: {self.seller.username}, Buyer: {self.buyer.username}, Product: {self.product.name} ({self.status})"

Smithy/seller/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from shop.models import Product
from django.contrib import messages

# Create your views here.

def dashboard(request):
    return render(request,'dashboard.html')


def products(request):
    productData = Product.objects.all()
    data = {
        'productData': productData
    }
    return render(request,'products.html',data)

def performance(request):
    return render(request,'performance.html')

def seller_orders(request):
    return render(request,'orders.html')

def seller_profile(request):
    return render(request,'profile.html')

def help_center(request):
    return render(request,'help_center.html')

def seller_delete(request):
    product_id = request.GET.get('product_id')
    Product.objects.filter(id=product_id).delete()
    messages.success(request, "Your item deleted from cart !!")
    return redirect('/products')


def add_products(request):
    current_user = request.user.username
    current_user_email = request.user.email

    if request.method == "POST":
        name = request.POST.get('pname')
        price = request.POST.get('pprice')
        discount = request.POST.get('pdiscount')
        category = request.POST.get('pcategory')
        quantity = request.POST.get('pquantity')
        image_file = request.FILES.get('pimg')
        description = request.POST.get('pdescription')
        new_product = Product.objects.create(
            name=name,
            price=price,
            discount=discount,
            quantity=quantity,
            category=category,
            product_image=image_file,
            description=description,
            seller = current_user,
            seller_email= current_user_email
        )
        new_product.save()
        return redirect('/products')
    return render(request, "add_products.html")

Smithy/seller/templates/add_products.html
{% extends 'seller_base.html' %} {% load static %} {% block content %}

<div class="top_navbar">
  <div class="col-auto hamburger">
    <a href="#">
      <i class="fas fa-bars"></i>
    </a>
  </div>
  <div class="col text-center">
    <h1>Add New <span class="text-success">Product</span></h1>
  </div>
</div>

<section>
 
  <div class="row">
    <div class="login_form" id="Signup_page">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <form action="#" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="overflow-scroll" style="max-height: 450px">

                
                <div class="input-field">
                  <input
                    type="text"
                    name="pname"
                    id=""
                    placeholder="Name"
                    required
                  />
                </div>
                <div class="input-field">
                  <input
                    type="number"
                    name="pprice"
                    id=""
                    placeholder="Price Of Product"
                    required
                  />
                </div>
                <div class="input-field">
                  <input
                    type="number"
                    name="pquantity"
                    placeholder="quantity"
                    required
                  />
                </div>
                <div class="input-field">
                  <input
                    type="number"
                    name="pdiscount"
                    placeholder="Discount Percentage"
                    required
                  />
                </div>

                <div class="input-field">
                  <input
                    list="browsers"
                    name="pcategory"
                    id="browser"
                    placeholder="Product Category"
                    required
                  />
                  <datalist id="browsers">
                    <option value="Tools"></option>
                    <option value="Agriculture"></option>
                    <option value="Weapones"></option>
                    <option value="Utensils"></option>
                  </datalist>
                </div>

                <div class="input-field">
                  <input
                    type="file"
                    id="img"
                    name="pimg"
                    accept="image/*"
                    required
                  />
                </div>
                <label for="exampleFormControlFile1">Choose Image</label>

                <div class="input-field">
                  <textarea
                    class="form-control"
                    id="exampleFormControlTextarea1"
                    rows="3"
                    placeholder="Product Discription"
                    name="pdescription"
                  ></textarea>
                </div>
              </div>

              <div class="heading">
                <button class="btn" type="submit">Add Product</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

Smithy/seller/templates/dashboard.html
{% extends 'seller_base.html' %}
{% load static %}
{% block content %}

<div class="top_navbar">
    <div class="col-auto hamburger">
      <a href="#">
        <i class="fas fa-bars"></i>
      </a>
    </div>
    <div class="col text-center">
        <h1 class="text-success">Dashboard</h1>
    </div>
  </div>
<section class="product" id="product">


    <div class="row mb-4">
        <div class="col-md-3">
          <div class="card text-center">
            <div class="card-body">
              <h3 class="card-title">Total Sales</h3>
              <p class="card-text">$10,000</p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card text-center">
            <div class="card-body">
              <h3 class="card-title">Orders</h3>
              <p class="card-text">50</p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card text-center">
            <div class="card-body">
              <h3 class="card-title">Inventory</h3>
              <p class="card-text">200</p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card text-center">
            <div class="card-body">
              <h3 class="card-title">Revenue</h3>
              <p class="card-text">$5,000</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col-lg-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Product Performance</h5>
                <canvas id="productPerformanceChart"></canvas>
              </div>
            </div>
          </div>
        <div class="col-lg-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Sales Analytics</h5>
              <canvas id="salesChart"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
      
  </div>


    

</section>
{% endblock %}

Smithy/seller/templates/help_center.html
{% extends 'seller_base.html' %}
{% load static %}
{% block content %}

<div class="top_navbar">
    <div class="col-auto hamburger">
      <a href="#">
        <i class="fas fa-bars"></i>
      </a>
    </div>
    <div class="col text-center">
      <h1>help  <span class="text-success">center</span></h1>
    </div>
  </div>

<section class="product" id="product">

    

    

</section>
{% endblock %}

Smithy/seller/templates/orders.html
{% extends 'seller_base.html' %}
{% load static %}
{% block content %}

<div class="top_navbar">
    <div class="col-auto hamburger">
      <a href="#">
        <i class="fas fa-bars"></i>
      </a>
    </div>
    <div class="col text-center">
      <h1>This is <span>Dashboard</span></h1>
    </div>
  </div>

<section class="product" id="product">

    <h1 class="heading">This is <span>orders Page</span></h1>

    

</section>
{% endblock %}

Smithy/seller/templates/performance.html
{% extends 'seller_base.html' %}
{% load static %}
{% block content %}

<div class="top_navbar">
    <div class="col-auto hamburger">
      <a href="#">
        <i class="fas fa-bars"></i>
      </a>
    </div>
    <div class="col text-center">
      <h1>Your <span class="text-success">Performance</span></h1>
    </div>
  </div>

<section class="product" id="product">

    
    <div class="row mb-4">
        <div class="col-lg-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Product Performance</h5>
                <canvas id="productPerformanceChart"></canvas>
              </div>
            </div>
          </div>
        <div class="col-lg-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Sales Analytics</h5>
              <canvas id="salesChart"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
    

</section>
{% endblock %}

Smithy/seller/templates/products.html
{% extends 'seller_base.html' %} {% load static %} {% block content %}

<div class="top_navbar">
  <div class="col-auto hamburger">
    <a href="#">
      <i class="fas fa-bars"></i>
    </a>
  </div>
  <div class="col text-center">
    <h1 >Your <span class="text-success">Products</span></h1>
  </div>
</div>

<section>
  
  <div class="row">
    <div class="overflow-scroll" style="max-height: 400px">
      {% for item in productData %}
      <div class="card mb-3">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <div class="d-flex flex-row align-items-center">
              <div>
                <img
                  src="/{{item.product_image}}"
                  class="img-fluid rounded-3"
                  alt="Shopping item"
                  style="width: 65px"
                />
              </div>
              <div class="ms-3">
                <h3>{{item.name}}</h3>
              </div>
            </div>
            <div class="d-flex align-items-center">
              <div class="price">
                <h3 class="mb-0">Rs.<span>{{item.discounted_price}}</span></h3>
              </div>
              <button type="submit" style="background: white">
                <i class="delete_btn fa fa-edit"></i>
              </button>

              <form action="/seller-delete">
                <input type="hidden" name="product_id" value="{{item.id}}" />
                <button type="submit" style="background: white">
                  <i class="delete_btn fa fa-trash"></i>
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="heading">
    <a href="{% url 'seller:add-products' %}" class="btn">Add Product</a>
  </div>
</section>
{% endblock %}

Smithy/seller/templates/profile.html
{% extends 'seller_base.html' %}
{% load static %}
{% block content %}


<div class="top_navbar">
    <div class="col-auto hamburger">
      <a href="#">
        <i class="fas fa-bars"></i>
      </a>
    </div>
    <div class="col text-center">
        <h1 >Your <span class="text-success">Profile</span></h1>
    </div>
  </div>

<section class="product" id="product">

   

    

</section>
{% endblock %}

Smithy/seller/templates/seller_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/static/css/seller_base.css" />
    <link rel="stylesheet" href="/static/css/seller_product.css" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1"></script>
  </head>

  <body>
    <div class="wrapper">
      <!--Top menu -->
      <div class="sidebar">
        <!--profile image & text-->
        <div class="profile">
          <img src="/static/photo/Photo.jpg" alt="profile_picture" />
          {% comment %} <i class="fas fa-user fa-10x"></i> {% endcomment %}
          <h3>{{user.username}}</h3>

          <p>Designer</p>
        </div>

        <!--menu item-->
        <ul class="list-unstyled">
          {% url 'seller:dashboard' as url %}
          <li class="{% if request.path == url %} active {% endif %}">
            <a href="{{url}}">
              <span class="icon"><i class="fas fa-desktop"></i></span>
              <span class="item">Dashboard</span>
            </a>
          </li>
          {% url 'seller:products' as url %}
          <li class="{% if request.path == url %} active {% endif %}">
            <a href="{{url}}">
              <span class="icon"><i class="fas fa-chart-line"></i></span>
              <span class="item">Products</span>
            </a>
          </li>
          {% url 'seller:performance' as url %}
          <li class="{% if request.path == url %} active {% endif %}">
            <a href="{{url}}">
              <span class="icon"><i class="fas fa-tachometer-alt"></i></span>
              <span class="item">Performance</span>
            </a>
          </li>
          <li class="dropdown">
            <a href="{{url}}">
              <span class="icon"><i class="fas fa-database"></i></span>
              <span class="item">Orders</span>
            </a>
            <div class="dropdown-content">
              <a href="#">
                <span class="icon"><i class="fas fa-plus"></i></span>
                <span class="item">New Orders</span>
              </a>
              <a href="#">
                <span class="icon"><i class="fas fa-spinner"></i></span>
                <span class="item">Processing</span>
              </a>
              <a href="#">
                <span class="icon"><i class="fas fa-check"></i></span>
                <span class="item">Completed</span>
              </a>
            </div>
          </li>

          {% url 'seller:seller-profile' as url %}
          <li class="{% if request.path == url %} active {% endif %}">
            <a href="{{url}}">
              <span class="icon"><i class="fas fa-user-friends"></i></span>
              <span class="item">My Profile</span>
            </a>
          </li>
          {% url 'seller:help-center' as url %}
          <li class="{% if request.path == url %} active {% endif %}">
            <a href="{{url}}">
              <span class="icon"><i class="fas fa-user-shield"></i></span>
              <span class="item">Help Center</span>
            </a>
          </li>

          <li>
            <a href="#">
              <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
              <label for="show" class="show-btn">Log Out</label>
            </a>
          </li>
        </ul>
      </div>
      <div class="section">{% block content %} {% endblock %}</div>
    </div>
    <script>
      var hamburger = document.querySelector(".hamburger");
      hamburger.addEventListener("click", function () {
        document.querySelector("body").classList.toggle("active");
      });
      function openForm() {
        document.getElementById("myForm").style.display = "block";
      }

      function closeForm() {
        document.getElementById("myForm").style.display = "none";
      }

      // Sales Analytics Chart
      var ctx = document.getElementById("salesChart").getContext("2d");
      var salesChart = new Chart(ctx, {
        type: "bar",
        data: {
          labels: ["January", "February", "March", "April", "May", "June"],
          datasets: [
            {
              label: "Sales",
              data: [5000, 6000, 4500, 7000, 8000, 5500],
              backgroundColor: "#27ae60",
              borderColor: "#2c2c54",
              borderWidth: 1,
            },
          ],
        },
        options: {
          responsive: true,
          scales: {
            y: {
              beginAtZero: true,
            },
          },
        },
      });
       // Product Performance Chart
    var ctx = document.getElementById('productPerformanceChart').getContext('2d');
    var productPerformanceChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ['Product A', 'Product B', 'Product C', 'Product D', 'Product E'],
        datasets: [{
          label: 'Sales',
          data: [100, 80, 120, 90, 110],
          backgroundColor: "#27ae60",
              borderColor: "#2c2c54",
          borderWidth: 1
        }]
      },
      options: {
        responsive: true,
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
    </script>
  </body>
</html>