Smithy/Smithy/urls.py
from django.contrib import admin
from django.urls import path, include
# hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('seller.urls')),
]

Smithy/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('tools/', views.tools, name='tools'),
    path('agriculture/', views.agriculture, name='agriculture'),
    path('weapones/', views.weapones, name='weapones'),
    path('utensils/', views.utensils, name='utensils'),
    path('login/', views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
    path('wishlist/',views.wishlist, name='wishlist'),
    path('logout/', views.logout_page, name="logout"),
    path('payment/', views.pay_now, name="payment"),
    path('profile/', views.profile, name="profile"),
    path('orders/', views.orders, name="orders"),

    
    path('product-details/<product_id>',views.product_details,name='product_details'),
    path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    path('cart/',views.show_cart,name='showcart'),
    path('delete-from-cart/',views.delete_from_cart,name='delete-from-cart'),
    path('increase_quantity/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease_quantity/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    

]

Smithy/templates/base.html
{% include "header.html" %}
    {% block content %}

    {% endblock %}

{%include "footer.html" %}

Smithy/templates/footer.html
    <!-- custom js file link  -->
    <script src="script.js"></script>

</body>

</html>

Smithy/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blacksmiths First Online Shop.</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'shop/style.css'%}">
    <link rel="stylesheet" href="{% static 'shop/cart.css'%}">

</head>

<body>



    <header>

        <div class="header-1">

            <a  class="logo "><i class='fas fa-hammer' style='font-size:36px'></i>Smithy</a>
            <form action="" class="search-box-container">
                <input type="search" id="search-box" placeholder="search here...">
                <label for="search-box" class="fas fa-search"></label>
            </form>
        </div>

        <div class="header-2">

            <div id="menu-bar" class="fas fa-bars"></div>

            <ul class="navbar" style="list-style-type:none;">

                {%url 'shop:index' as url %}
                <li class="{% if request.path == url %} active {% endif %}"><a  href="{{url}}">home</a></li>
                {%url 'shop:tools' as url %}
                <li class="{% if request.path == url %} active {% endif %}"><a href="{{url}}">tools</a></li>
                {%url 'shop:agriculture' as url %}
                <li class="{% if request.path == url %} active {% endif %}"><a href="{{url}}">Agriculture</a></li>
                {%url 'shop:weapones' as url %}
                <li class="{% if request.path == url %} active {% endif %}"><a href="{{url}}">Weapones</a></li>
                {%url 'shop:utensils' as url %}
                <li class="{% if request.path == url %} active {% endif %}"><a href="{{url}}">utensils</a></li>
                
                {% comment %} <a href="#category">category</a>
                <a href="#product">product</a>
                <a href="#contact">contact</a> {% endcomment %}
            </ul>

            <div class="icons">
                
                {% if user.is_authenticated %}
                <a href="{% url 'shop:showcart' %}"><i class="fas fa-shopping-cart"></i></a>
                <a href="{% url 'shop:wishlist' %}" class="fas fa-heart"></a>
                <a class="fas fa-user-circle" id="dropdownMenuLink" data-bs-toggle="dropdown"></a>
                {% comment %} <a href="#"><span>{{user.username}}</span></a> {% endcomment %}
                <div class="dropdown-menu" id="profile-dropdown_box" aria-labelledby="dropdownMenuLink">
                    
                    
                    <a class="dropdown-item" href="#"">Welcome {{user.username}}</a>
                    <hr class="dropdown-divider">
                    <a class="dropdown-item " href="{% url 'shop:profile' %}"><span>My Profile</span></a>
                    <a class="dropdown-item " href="{% url 'shop:orders' %}"><span>Orders</span> </a>
                    <hr class="dropdown-divider">
                    <a class="dropdown-item " href="{% url 'shop:logout' %}"><span>Logout</span> </a>
                </div>
                    {% comment %} <a class="dropdown-item " href="{% url 'shop:logout'%}"><span>Logout</span></a> {% endcomment %}
                    {%else%}
                    
                    {% comment %} <a   data-bs-toggle="modal" data-bs-target="#Login_page">
                        login
                    </a> {% endcomment %}

                    <a class="dropdown-item " href="{% url 'shop:login' %}"><span>Login</span> </a>
                    {%endif%}
                
                

            </div>

        </div>

    </header>

    {% block content %}

    {% endblock %}




    <!-- custom js file link  -->
    <script src="script.js"></script>

</body>

</html>