Smithy/Smithy/urls.py
from django.contrib import admin
from django.urls import path, include
# hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('', include('seller.urls')),
]

Smithy/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('tools/', views.tools, name='tools'),
    path('agriculture/', views.agriculture, name='agriculture'),
    path('weapones/', views.weapones, name='weapones'),
    path('utensils/', views.utensils, name='utensils'),
    path('login/', views.login_page, name='login'),
    path('signup/', views.signup_page, name='signup'),
    path('wishlist/',views.wishlist, name='wishlist'),
    path('logout/', views.logout_page, name="logout"),
    path('payment/', views.pay_now, name="payment"),
    path('profile/', views.profile, name="profile"),
    path('orders/', views.orders, name="orders"),

    
    path('product-details/<product_id>',views.product_details,name='product_details'),
    path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    path('cart/',views.show_cart,name='showcart'),
    path('delete-from-cart/',views.delete_from_cart,name='delete-from-cart'),
    path('increase_quantity/<int:item_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease_quantity/<int:item_id>/', views.decrease_quantity, name='decrease_quantity'),
    

]

Smithy/cart/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product


# Create your models here.
class Cart (models.Model):
    user = models. ForeignKey (User, on_delete=models.CASCADE)
    product = models. ForeignKey (Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    @property
    def price(self):
        return self.product.discounted_price

    @property
    def total_cost (self):
        return self.quantity * self.product.discounted_price

Smithy/shop/models.py
from django.db import models

# Create your models here.

# CATEGORY_CHOICES = (
#     ('T', 'Tools'),
#     ('A', 'Agriculture'),
#     ('W', 'Weapones'),
#     ('U', 'Utensils'),

# )



class Product(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    discount = models.IntegerField(default=0)
    discounted_price = models.FloatField(default=0)
    description = models.TextField(blank= True, null=True, unique = True)
    category = models.CharField(max_length=100)
    product_image = models.ImageField(upload_to='static/image/')
    quantity=models.IntegerField(default=1)
    seller = models.CharField(default='NA',max_length=100)
    seller_email = models.CharField(default='NA',max_length=100)

    def __str__(self):
        return self.name
    @property
    def discounted_price(self):
        discount_amount = (self.price * self.discount) / 100
        discounted_price = self.price - discount_amount
        return discounted_price


class Payment(models.Model):
    name = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=100)
    paid = models.BooleanField(default=False)
    def __str__(self):
        return self.name

Smithy/cart/views.py
from django.shortcuts import render

# Create your views here.

Smithy/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import response,HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User, auth
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from shop.models import Product, Payment
from cart.models import *
from django.contrib.auth.decorators import login_required
import razorpay

# @login_required(login_url='shop:login')
# Create your views here.

# @login_required(login_url='shop:login')
def index(request):
    productData = Product.objects.all().exclude()[:10]
    data = {
        'productData' : productData
    }
    return render(request, 'shop/index.html', data)

# @login_required(login_url='shop:login')
def tools(request):
    productData = Product.objects.filter(category='T')
    # productData = Product.objects.all()
    data = {
        'productData' : productData
    }
    return render(request, 'shop/tools.html', data)

# @login_required(login_url='shop:login')
def weapones(request):
    productData = Product.objects.filter(category='W')
    # productData = Product.objects.all()
    data = {
        'productData' : productData
    }
    return render(request, 'shop/weapones.html', data)

# @login_required(login_url='shop:login')
def agriculture(request):
    productData = Product.objects.filter(category='A')
    # productData = Product.objects.all()
    data = {
        'productData' : productData
    }
    return render(request, 'shop/agriculture.html', data)

# @login_required(login_url='shop:login')
def utensils(request):
    productData = Product.objects.filter(category='U')
    # productData = Product.objects.all()
    data = {
        'productData' : productData
    }
    return render(request, 'shop/utensils.html', data)
# @login_required(login_url='shop:login')
def cart(request):
    cartData = Cart.objects.all()
    data = {
        'cartData': cartData
    }
    return render(request, 'shop/cart.html', data)

def success(request):
    return render(request, 'shop/payment_page.html')


# @login_required(login_url='shop:login')
def wishlist(request):
    return render(request, 'shop/wishlist.html')

@login_required(login_url='shop:login')
def payment(request):
    return render(request, 'shop/payment_page.html')

@login_required(login_url='shop:login')
def profile(request):
    return render(request, 'shop/profile_page.html')

@login_required(login_url='shop:login')
def orders(request):
    return render(request, 'shop/orders_page.html')



def login_page(request):
    user_name=''
    if request.method == "POST":
        username = request.POST.get('username')
        pass1 = request.POST.get('password')
        user=authenticate(request,username=username,password=pass1)
        if user is not None:
            login(request, user)
            return redirect('shop:index')
        else:
            return HttpResponse("Invalid input");

    return render(request, "shop/login_page.html",{'uname':user_name})


def signup_page(request):
    x=""
    if request.method == "POST":
        uname = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        print(uname,email,password1,password2)
        if password1 != password2:
            x="Password not match !!"
            return render(request,"shop/signup_page.html",{'output':x})
        else:
            print(uname,email,password1,password2)
            new_user=User.objects.create_user(uname,email,password1)
            new_user.save()
            return redirect('shop:login')
    return render(request,"shop/signup_page.html")

def logout_page(request):
    logout(request)
    return redirect('/')


def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('product_id')
    product = get_object_or_404(Product, id=product_id)
    if Cart.objects.filter(user=user, product=product).exists():
        return redirect('/cart')
    Cart(user=user, product=product).save()
    return redirect('/cart')



def pay_now(request):
    user=request.user 
    cart= Cart.objects.filter(user=user)
    amount = 0
    shiping_amount = 40
    l= len(cart)
    for p in cart:
        value = p.quantity * p.product.discounted_price
        amount = amount + value
    totalamount = amount + shiping_amount
    name = request.user
    amount = totalamount * 100
    client = razorpay.Client(auth=("rzp_test_bWZe5HkNf0YSKY", "igcgehbcVvTyxih0oPf2k9Q3"))
    payment = client.order.create({'amount':amount, 'currency':'INR', 'payment_capture':'1'})
    print(payment)
    pay = Payment(name=name, amount = amount, payment_id = payment['id'])
    pay.save()
    return render(request,'shop/payment_page.html',locals())

def show_cart(request):
    user=request.user 
    cart= Cart.objects.filter(user=user)
    amount = 0
    shiping_amount = 40
    l= len(cart)
    for p in cart:
        value = p.quantity * p.product.discounted_price
        amount = amount + value
    totalamount = amount + shiping_amount
    return render(request,'shop/cart.html',locals())


def delete_from_cart(request):
   product_id=request.GET.get('product_id')
   Cart.objects.filter(id=product_id).delete()
   messages.success(request,"Your item deleted from cart !!")
   return HttpResponseRedirect('/cart')



def increase_quantity(request, item_id):
    cart_item = get_object_or_404(Cart, id=item_id)
    cart_item.quantity += 1
    cart_item.save()

    return redirect('/cart')


def decrease_quantity(request, item_id):
    cart_item = get_object_or_404(Cart, id=item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()

    return redirect('/cart')

def product_details(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    similar_products = Product.objects.filter(
        category=product.category).exclude(id=product.id)[:4]

    context = {
        'product_details': product,
        'similar_products': similar_products,
    }

    return render(request, 'shop/product_details.html', context)

Smithy/shop/templates/shop/agriculture.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   
    <section class="product" id="product">

        <h1 class="heading">Select Your <span>Agriculture Weapones</span></h1>

        <div class="box-container">
            {% for n in productData %}
            
            <div class="box">
                <span class="discount">-{{n.percentage}}%</span>
                <img src="/{{n.product_image}}" alt="image" >
                <h3>{{n.title}}</h3>
                <div class="price"> Rs {{n.discounted_price}} <span> Rs {{n.selling_price}} </span> </div>
                <div class="quantity">
                    <span>quantity : </span>
                    <input type="number" min="1" max="1000" value="1">
    
                </div>
                <a href="{% url 'shop:product_details' n.id %}" class="btn">Order Now</a>
            </div>
            {% endfor %}
        </div> 

    </section>
{% endblock %}

Smithy/shop/templates/shop/cart.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section>
  {% if l == 0 %}
  <div class="heading">Your <span class="title">Cart</span> is Empty .</div>
  {% else %}
  <div class="heading">
    Your
    <span class="title">Cart</span>
  </div>
  <div class="row">
    <div class="overflow-scroll" style="max-height: 400px">
      {% for item in cart %}
      <div class="card mb-3">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <div class="d-flex flex-row align-items-center">
              <div>
                <a href="{% url 'shop:product_details' item.product.id %}" >
                <img
                  src="/{{item.product.product_image}}"
                  class="img-fluid rounded-3"
                  alt="Shopping item"
                  style="width: 65px"
                />
              </a>
              </div>
              <div class="ms-3">
                <h3>{{item.product.name}}</h3>
              </div>
            </div>
            <div class="d-flex align-items-center">
              <div class="quantity d-flex align-items-center">
                <span>quantity : </span>
                <form
                  action="{% url 'shop:decrease_quantity' item.id %}"
                  method="post"
                  style="display: inline"
                  
                >
                  {% csrf_token %}
                  <button  type="submit"><i class="delete_btn fa fa-minus" style="font-size: 30px; background: white"></i></button>
                </form>
                <input type="number" style="width:50px" value="{{item.quantity}}" />
                <form
                  action="{% url 'shop:increase_quantity' item.id %}"
                  method="post"
                  style="display: inline"
                >
                  {% csrf_token %}
                  <button type="submit"><i class="delete_btn fa fa-plus" style="font-size: 30px; background: white"></i></button>
                </form>
              </div>

              <div class="price">
                <h3 class="mb-0">
                  Rs.<span>{{item.product.discounted_price}}</span>
                </h3>
              </div>
              <form action="/delete-from-cart">
                <input type="hidden" name="product_id" value="{{item.id}}" />
                <button type="submit">
                  <i class="delete_btn fa fa-trash" style="font-size: 30px; background: white"></i>
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="heading">
    <div class="card-body">
      <h2>The total amount of</h2>

      <div class="d-flex justify-content-start align-items-center">
        <h4>Amount</h4>
      </div>
      <div class="d-flex justify-content-end align-items-center">
        <h4>Rs. {{amount}}</h4>
      </div>

      <div class="d-flex justify-content-start align-items-center">
        <h4>Shipping</h4>
      </div>
      <div class="d-flex justify-content-end align-items-center">
        <h4>Rs. {{shiping_amount}}</h4>
      </div>

      <hr class="my-4" />
      <div class="d-flex justify-content-between mb-4">
        <h4 class="mb-2">Total(Incl. taxes)</h4>
        <h4 class="mb-2">Rs. {{totalamount}}</h4>
      </div>
    </div>
    
    <a href="{% url 'shop:payment' %}" class="btn">Pay Now</a>
  </div>
  {% endif %}
</section>

{% endblock %}

Smithy/shop/templates/shop/index.html

{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="home" id="home">

    <div class="image">
        <img src="{% static 'shop/image/logo3.png'%}" alt="">
    </div>

    <div class="content">
        <span>Iron's and Cooper's</span>
        <h3>your daily need products</h3>
        <a href="#" class="btn">get started</a>
    </div>

</section>



<section class="banner-container">

    <div class="banner">
        <img src="images/hammer.png" alt="">
        <div class="content">
            <h3>special offer</h3>
            <p>upto 45% off</p>
            <a href="#" class="btn">check out</a>
        </div>
    </div>

    <div class="banner">
        <img src="images/banner-2.jpg" alt="">
        <div class="content">
            <h3>limited offer</h3>
            <p>upto 50% off</p>
            <a href="#" class="btn">check out</a>
        </div>
    </div>

</section>



<section class="category" id="category">

    <h1 class="heading">shop by <span>category</span></h1>

    <div class="box-container">

        <div class="box">
            <h3>Tools</h3>
            <p>upto 50% off</p>
            <img src="images/tools/Hammer.png" alt="">
            <a href="{% url 'shop:tools' %}" class="btn">shop now</a>
        </div>
        <div class="box">
            <h3>Agriculture</h3>
            <p>upto 44% off</p>
            <img src="images/agriculture/Pickaxe.png" alt="">
            <a href="{% url 'shop:agriculture' %}" class="btn">shop now</a>
        </div>
        <div class="box">
            <h3>Weapones</h3>
            <p>upto 35% off</p>
            <img src="images/weapons/Club Weapon.png" alt="">
            <a href="{% url 'shop:weapones' %}" class="btn">shop now</a>
        </div>
        <div class="box">
            <h3>Utensils</h3>
            <p>upto 12% off</p>
            <img src="images/Utensils/stainless-steel-utensils-06-500x500-removebg-preview.png" alt="">
            <a href="{% url 'shop:utensils' %}" class="btn">shop now</a>
        </div>

    </div>

</section>



<section class="product" id="product">

    <h1 class="heading">latest <span>products</span></h1>
    <div class="box-container">
        {% for n in productData %}
        <div class="box">
            <span class="discount">-{{n.percentage}}%</span>
            <img src="/{{n.product_image}}" alt="image" >
            <h3>{{n.title}}</h3>
            <div class="price"> Rs {{n.discounted_price}} <span> Rs {{n.selling_price}} </span> </div>
            <div class="quantity">
                <span>quantity : </span>
                <input type="number" min="1" max="1000" value="1">

            </div>
            <a href="#" class="btn">add to cart</a>
        </div>
        {% endfor %}
    </div>

</section>




<section class="contact" id="contact">

    <h1 class="heading"> <span>contact</span> us </h1>

    <form action="">

        <div class="inputBox">
            <input type="text" placeholder="Name">
            <input type="email" placeholder="Email">
        </div>

        <div class="inputBox">
            <input type="number" placeholder="Number">
            <input type="text" placeholder="Subject">
        </div>

        <textarea placeholder="Message" name="" id="" cols="30" rows="10"></textarea>

        <input type="submit" value="send message" class="btn">

    </form>

</section>
{% endblock %}

Smithy/shop/templates/shop/login_page.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="col-lg-7">
  <div class="login_form" id="Login_page">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Login</h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <form action="#" method="post">
            {% csrf_token %}
            <div class="input-field">
              <input
                type="text"
                name="username"
                id=""
                placeholder="Enter your user name"
                required
              />
              <i class="uil uil-envelope"></i>
            </div>
            <div class="input-field">
              <input
                type="password"
                name="password"
                id=""
                placeholder="Enter your password"
                required
              />
              <i class="uil uil-lock icon"></i>
              <i class="uil uil-eye-slash showHidenPw"></i>
            </div>

            <div class="checkbox-text">
              <div class="checkbox-content">
                <input type="checkbox" id="logCheck" />
                <label for="logCheck" class="text">Remember me</label>
              </div>
              <div>
                <a href="#" class="text">Forgot password?</a>
              </div>
            </div>

            <div class="input-field button">
              <input type="submit" value="Login Now" />
            </div>

            <div class="login-signup">
              <span class="text"
                >Don't have an account ?
                <a data-bs-toggle=" modal" href="{% url 'shop:signup' %}"
                  >Signup now</a
                >
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

Smithy/shop/templates/shop/orders_page.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section>
  <div class="heading">
    Your
    <span class="title"> Orders </span>
  </div>
  
</section>
{% endblock %}

Smithy/shop/templates/shop/payment_page.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section>
  <div class="heading">
    this is your
    <span class="title">payment </span>
    page
  </div>
</section>
{% if payment %}
<div class="text-center mx-auto">
  <form action="/payment_page.html" method="POST">
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
      var options = {
        key: "rzp_test_bWZe5HkNf0YSKY",
        amount: "{{payment.amount}}",
        currency: "INR",
        name: "{{payment.name}}",
        description: "Test Transaction",
        image: "https://example.com/your_logo",
        order_id: "{{payment.id}}",
        callback_url: "{{callback_url}}",
        redirect: true,
        prefill: {
          name: "Vipin Yadav",
          email: "smithy@gamil.com",
          contact: "9999999999",
        },
        notes: {
          address: "Razorpay Corporate Office",
        },
        theme: {
          color: "#3399cc",
        },
      };
      var rzp1 = new Razorpay(options);
      rzp1.open();
    </script>
    <input type="hidden" custom="Hidden Element" name="hidden" />
  </form>
</div>
{% endif %} {% endblock %}

Smithy/shop/templates/shop/product_details.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Product section-->
<section class="product">
  <div class="box-container container px-4 px-lg-5 my-5">
    <div class="row gx-4 gx-lg-5 align-items-center">
      <div class="col-md-4">
        <img
          class="card-img-top mb-5 mb-md-0"
          src="/{{product_details.product_image}}"
          alt="..."
        />
      </div>
      <div class="col-md-8">
        {% if product_details.discount > 0 %}
        <span class="discount">-{{product_details.discount}}%</span>
        {% endif %}
        <h1 class="display-1 fw-bolder">{{product_details.name}}</h1>
        <div class="fs-5 mb-5">
          {% if product_details.discount > 0 %}
          <span class="text-decoration-line-through"
            >₹ {{product_details.price}}</span
          >
          {% endif %}
          <span>₹{{product_details.discounted_price}}</span>
        </div>
        <p class="display-6">{{product_details.description | safe}}</p>
        <div class="d-flex">
          <div class="d-flex">
            <form action="/add-to-cart">
              <input
                type="hidden"
                name="product_id"
                value="{{product_details.id}}"
              />
              <button class="btn" type="submit">
                <i class="bi-cart-fill me-1"></i>
                Add to cart
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Related items section-->
<section class="py-5 bg-light">
  <div class="container px-4 px-lg-5 mt-5">
    <h2 class="fw-bolder mb-4">Related products</h2>
    <div
      class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center"
    >
      {% for similar_product in similar_products %}

      <div class="col mb-5">
        <div class="card h-100">
          <!-- Sale badge-->
          <div
            class="badge bg-dark text-white position-absolute"
            style="top: 0.5rem; right: 0.5rem"
          >
           - {{similar_product.discount}} %
          </div>
          <!-- Product image-->
          <img
            class="card-img-top"
            src="/{{similar_product.product_image}}"
            alt="..."
          />
          <!-- Product details-->
          <div class="card-body p-4">
            <div class="text-center">
              <!-- Product name-->
              <h5 class="fw-bolder">{{similar_product.name}}</h5>
              <!-- Product reviews-->
              <div
                class="d-flex justify-content-center small text-warning mb-2"
              >
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
              <!-- Product price-->
              <span class="text-muted text-decoration-line-through"
                >Rs. {{similar_product.price}}</span
              >
              Rs. {{similar_product.discounted_price}}
            </div>
          </div>
          <!-- Product actions-->
          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
                <a href="{% url 'shop:product_details' similar_product.id %}" class="btn">Order Now</a>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <li>No similar products found.</li>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

Smithy/shop/templates/shop/profile_page.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section>
  <div class="heading">
    User
    <span class="title"> Details </span>
  </div>
  
</section>
{% endblock %}

Smithy/shop/templates/shop/signup_page.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="col-lg-7">
  <div class="login_form" id="Signup_page">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Registration</h5>
          {% comment %}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
          {% endcomment %}
        </div>
        <div class="modal-body">
          {% comment %}
          <div class="container">
            {% endcomment %}
            <form action="#" method="post">
              {% csrf_token %}
              <div class="input-field">
                <input
                  type="text"
                  name="username"
                  id=""
                  placeholder="User Name"
                  required
                />
                <i class="fa-regular fa-circle-user"></i>
              </div>
              <div class="input-field">
                <input
                  type="mail"
                  name="email"
                  id=""
                  placeholder="Enter your email"
                  required
                />
                <i class="uil uil-envelope"></i>
              </div>
              <div class="input-field">
                <input
                  type="password"
                  name="password1"
                  class="password"
                  placeholder="Create a password"
                  required
                />
                <i class="uil uil-lock icon"></i>
              </div>
              <div class="input-field">
                <input
                  type="password"
                  name="password2"
                  class="password"
                  placeholder="Confirm a password"
                  required
                />
                <i class="uil uil-lock icon"></i>
                <i class="uil uil-eye-slash showHidenPw"></i>
              </div>

              {% if output is not None %}
              <div class="input_field passnot_match">
                <span class="text">{{output}}</span>
              </div>
              {% endif %}

              <div class="input-field button">
                <input type="submit" value="Register Now" />
              </div>

              <div class="login-signup">
                <span class="text"
                  >Already have an account?
                  <a data-bs-toggle=" modal" href="{% url 'shop:login' %}"
                    >Login now</a
                  >
                </span>
              </div>
            </form>

            {% comment %}
          </div>
          {% endcomment %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

Smithy/shop/templates/shop/tools.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="product" id="product">

    <h1 class="heading">Select Your <span>Tools</span></h1>

    <div class="box-container">
        {% for n in productData %}
        
        <div class="box">
            <span class="discount">-{{n.percentage}}%</span>
            <img src="/{{n.product_image}}" alt="image">
            <h3>{{n.title}}</h3>
            <div class="price"> Rs {{n.discounted_price}} <span> Rs {{n.selling_price}} </span> </div>
            <div class="quantity">
                <span>quantity : </span>
                <input type="number" min="1" max="1000" value="1">

            </div>
            <a href="{% url 'shop:product_details' n.id %}" class="btn">Order Now</a>
        </div>
        
        {% endfor %}
    </div>

</section>
{% endblock %}

Smithy/shop/templates/shop/utensils.html
{% extends 'base.html' %} {% load static %} {% block content %} {% comment %}
<section class="categories" id="category">
  <div class="spice-image">
    <img src="" alt="" />
  </div>
</section>
{% endcomment %}
<section class="product" id="product">
  <h1 class="heading">Select Your <span>utensils</span></h1>

  <div class="box-container">
    {% for n in productData %}
    
    <div class="box">
        <span class="discount">-{{n.percentage}}%</span>
        <img src="/{{n.product_image}}" alt="">
        <h3>{{n.title}}</h3>
        <div class="price"> Rs {{n.discounted_price}} <span> Rs {{n.selling_price}} </span> </div>
        <div class="quantity">
            <span>quantity : </span>
            <input type="number" min="1" max="1000" value="1">

        </div>
        <a href="{% url 'shop:product_details' n.id %}" class="btn">Order Now</a>
    </div>
    
    {% endfor %}
</div>  
</section>
{% endblock %}

Smithy/shop/templates/shop/weapones.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<section class="product" id="product">
  <h1 class="heading">Select Your <span>Weapones</span></h1>
  <div class="box-container">
    {% for n in productData %}
    <div class="box">
      <span class="discount">-{{n.percentage}}%</span>
      <img src="/{{n.product_image}}" alt="" />
      <h3>{{n.title}}</h3>
      <div class="price">
        Rs {{n.discounted_price}} <span> Rs {{n.selling_price}} </span>
      </div>
      <div class="quantity">
        <span>quantity : </span>
        <input type="number" min="1" max="1000" value="1" />
      </div>
      <a href="{% url 'shop:product_details' n.id %}" class="btn">Order Now</a>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

Smithy/shop/templates/shop/wishlist.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section>
  <div class="heading">
    Wish
    <span class="title"> list </span>
  </div>
  
</section>
{% endblock %}